services:
  app:
    build:
      context: .
      dockerfile: /Users/keisukekubota/Programs/docker-dev/python/Dockerfile
    image: python-dev-docker-image:latest
    container_name: python-dev-container
    volumes:
      - .:/app
    tty: true